package dashboardcw;

import java.awt.Color;
import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdulrahman Ibrahim
 */
public class Login_Page_Project extends javax.swing.JFrame {
    public String username = "";
    public encryptionDecr ser = new encryptionDecr("a1djwlqa1djwlq32");
    public String userNameDashboard = "";

    /**
     * Creates new form Login_Page_Project
     */
    public Login_Page_Project() {
        initComponents();
        
        // we want to center the form so we will use the following coding.
        this.setLocationRelativeTo(null);
        
        // Creating a border for the Login Page title of the form for decoration purpose.
        Border Login_Page = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        Title_Login_Page.setBorder(Login_Page);
        
        
        
        
    }
    public Login_Page_Project(String getUsername){
         initComponents();
    }
    
    public String getLogInDateTime(String username){
        PreparedStatement i;
        ResultSet y;
        Date s;
        String query = "";
        userNameDashboard = username;
        return userNameDashboard;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Username_Login = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Password_Login = new javax.swing.JPasswordField();
        Login_Button = new javax.swing.JButton();
        Register_Label = new javax.swing.JLabel();
        Title_Login_Page = new javax.swing.JPanel();
        Login_Page = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setText("Username");

        Username_Login.setForeground(new java.awt.Color(204, 204, 204));
        Username_Login.setText("username");
        Username_Login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Username_LoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Username_LoginFocusLost(evt);
            }
        });

        jLabel2.setText("Password");

        Password_Login.setForeground(new java.awt.Color(204, 204, 204));
        Password_Login.setText("password");
        Password_Login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Password_LoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Password_LoginFocusLost(evt);
            }
        });
        Password_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_LoginActionPerformed(evt);
            }
        });

        Login_Button.setText("Login");
        Login_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Login_ButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Login_ButtonMouseEntered(evt);
            }
        });
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });

        Register_Label.setText("Sign Up");
        Register_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Register_LabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Register_LabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Register_LabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Login_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Username_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Password_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Register_Label)
                .addGap(264, 264, 264))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username_Login)
                    .addComponent(Password_Login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(Register_Label)
                .addContainerGap())
        );

        Title_Login_Page.setBackground(new java.awt.Color(255, 204, 0));

        Login_Page.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Login_Page.setText("Sign In");

        javax.swing.GroupLayout Title_Login_PageLayout = new javax.swing.GroupLayout(Title_Login_Page);
        Title_Login_Page.setLayout(Title_Login_PageLayout);
        Title_Login_PageLayout.setHorizontalGroup(
            Title_Login_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Title_Login_PageLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(Login_Page)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Title_Login_PageLayout.setVerticalGroup(
            Title_Login_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Title_Login_PageLayout.createSequentialGroup()
                .addComponent(Login_Page)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Title_Login_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Title_Login_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Password_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_LoginActionPerformed

    private void Username_LoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_LoginFocusGained
        // TODO add your handling code here:
        // setting clear if user clicks and the text is == username 
        if(Username_Login.getText().trim().toLowerCase().equals("username")){
            Username_Login.setText("");
            Username_Login.setForeground(Color.black);
            
        }
    }//GEN-LAST:event_Username_LoginFocusGained

    private void Username_LoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_LoginFocusLost
        // TODO add your handling code here:
        
        if(Username_Login.getText().equals("") || Username_Login.getText().trim().toLowerCase().equals("username")){
            Username_Login.setText("username");
            Username_Login.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_Username_LoginFocusLost

    private void Password_LoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_LoginFocusGained
        // TODO add your handling code here:
        
        String PasswordLogin = String.valueOf(Password_Login.getPassword());
        if(PasswordLogin.trim().toLowerCase().equals("password")){
           Password_Login.setText("");
            Password_Login.setForeground(Color.black);
            
        }
    }//GEN-LAST:event_Password_LoginFocusGained

    private void Password_LoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_LoginFocusLost
        // TODO add your handling code here:
         String PasswordLogin = String.valueOf(Password_Login.getPassword());
         if(PasswordLogin.equals("") || PasswordLogin.trim().toLowerCase().equals("password")){
            Password_Login.setText("password");
           Password_Login.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_Password_LoginFocusLost

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        //Declaring variables which will help us to compare the user input with 
        //out database system.
        PreparedStatement e;
        ResultSet x;
        PreparedStatement managerE;
        ResultSet managerX;
        SimpleDateFormat formatter= new SimpleDateFormat("HH:mm:ss_yy-MM-dd");
        Date date = new Date(System.currentTimeMillis());
        String p = formatter.format(date);
        
        boolean checking = true;
             

        //UserLog s1 = new UserLog();
        
       
        
        //Getting username and passwords from user input in the JFRAME
        String userName = Username_Login.getText();
        String password = String.valueOf(Password_Login.getPassword());
        //s1.setLogoutDate(userName);
        
        //Checking if password and usernames exist in our database system
        //And which database include the matching details(Manager) or (Client)
        //Those are two queries:
        String checkDatabase = "SELECT * FROM Users WHERE Username = ? AND Password = ? ";
         String checkDatabaseManager = "SELECT * FROM `Managers` WHERE `Username` = ? AND `Password` = ?";
        PreparedStatement ps = null;
        
        try 
        {
            
             String checkLogIn = "UPDATE  Users set LogInDate = ? where Username= ? ";
            ps = My_Database.getConnection().prepareStatement(checkLogIn);
            ps.setString(1, p); 
            ps.setString(2, userName); 
            int i = ps.executeUpdate();
            if (i > 0) 
            { 
                System.out.println("Product Updated"); 
                System.out.println(userName);
                UserLog s1 = new UserLog(userName);
                userNameDashboard = userName;
                System.out.println(userNameDashboard);
                getLogInDateTime(userName);
                
                
            } 
            else 
            {
                System.out.println("Error Occured");
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(Login_Page_Project.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(Login_Page_Project.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        
        
        boolean  s = false;
       
        try 
        {
//            UserLog lop = new UserLog();
//            UserLog lop1 = new UserLog();
           e = My_Database.getConnection().prepareStatement(checkDatabaseManager);
            
            
           
            e.setString(1, userName);
            e.setString(2, password);
           
            x = e.executeQuery();
             
//            lop.LoggingTester();
//            lop1.LoggingTester();

                if(x.next())
                {

                    //Show a new form
                    ManagerDashboard d1 = new ManagerDashboard();
                    d1.setVisible(true);
                    d1.pack();
                    d1.setLocationRelativeTo(null);

                    //close the login page once the dashboard is opened.

                    this.dispose();

                    s = true;
                }
                else
                {
                s = false;
                
                    try 
                    {
                        password = ser.encryptData(password);
//                        UserLog lop2 = new UserLog();
//                        UserLog lop3 = new UserLog();
                        e = My_Database.getConnection().prepareStatement(checkDatabase);
                        
                        e.setString(1, (userName));
                        e.setString(2, (password));


                        x = e.executeQuery();
//                        lop2.LoggingTester();
//                        lop3.LoggingTester();
                
                   
                        if(x.next())
                        {
                            
                                

                            // p = date.toString();
                            //  e.setString(1, p);

                            //Show a new form
                            DataDashboard d1 = new DataDashboard(userName);
                            //new  DataDashboard(userName).setVisible(true);
                            d1.setVisible(true);
                            d1.pack();
                            d1.setLocationRelativeTo(null);

                            //close the login page once the dashboard is opened.

                            this.dispose();  
                        }
                        else
                        {
                            //error message

                            JOptionPane.showMessageDialog(null, "Wrong Username or Password", "Error", 2);
                        }
                    }
                    catch (Exception ex) 
                    {
                        Logger.getLogger(Login_Page_Project.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            
        }
        catch (SQLException ex) 
        {
            Logger.getLogger(Login_Page_Project.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (Exception ex)
        {
            Logger.getLogger(Login_Page_Project.class.getName()).log(Level.SEVERE, null, ex);
        }
   
        
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void Login_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_ButtonMouseEntered
        // TODO add your handling code here:
        Login_Button.setBackground(Color.blue);
    }//GEN-LAST:event_Login_ButtonMouseEntered

    private void Login_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_ButtonMouseExited
        // TODO add your handling code here:
        Login_Button.setBackground(Color.GRAY);
    }//GEN-LAST:event_Login_ButtonMouseExited

    private void Register_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_LabelMouseEntered
        // TODO add your handling code here:
        Border Register_Page = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.black);
        Register_Label.setBorder(Register_Page);
    }//GEN-LAST:event_Register_LabelMouseEntered

    private void Register_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_LabelMouseExited
        // TODO add your handling code here:
        Register_Label.setBorder(null);
    }//GEN-LAST:event_Register_LabelMouseExited

    private void Register_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_LabelMouseClicked
        //When the user click to the label to register, the register page will become avauilable.
        
        Register_Page newPage = new Register_Page();
        newPage.setVisible(true);
        newPage.pack();
        newPage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        this.dispose();
        
        
    }//GEN-LAST:event_Register_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page_Project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login_Button;
    private javax.swing.JLabel Login_Page;
    private javax.swing.JPasswordField Password_Login;
    private javax.swing.JLabel Register_Label;
    private javax.swing.JPanel Title_Login_Page;
    private javax.swing.JTextField Username_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}

//I used the following referenshed to understand how can i run queries and create queries in java
//References
//Mysql, M. 2019. 62 Using JDBC Statement Objects to Execute SQL. [Online]. [5 March 2020]. 
//Available from: https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-usagenotes-statements.html

//Byrne, S. 2014. Java- MySQL Connection (Create Table, Insert, Select). [Online]. [5 March 2020]. 
//Available from: https://www.youtube.com/watch?v=KRhv4iPgzHE
